/*
 * The MIT License
 *
 * Copyright 2017 Aleksandr Malikov <schn27@gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package schn27.imutest;

import java.time.Duration;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;
import schn27.imutest.device.Link;
import schn27.serial.Com;

/**
 *
 * @author Aleksandr Malikov <schn27@gmail.com>
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		initComponents();
		initPortList();
		
		consoleOut.setModel(new DefaultListModel());
		
		gitVersion.setText(getVersionString());
		
		portName.addPopupMenuListener(new PopupMenuListener() {
			@Override
			public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
				initPortList();
			}

			@Override
			public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {}

			@Override
			public void popupMenuCanceled(PopupMenuEvent e) {}
		});

		charts = new Charts(chartsPanel, Duration.ofSeconds(3), Duration.ofMillis(19),
				new String[]{"Gyro X", "Gyro Y", "Gyro Z"}, 0.01);
	}
	
	private void initPortList() {
		Object selected = portName.getSelectedItem();
		
		portName.removeAllItems();
		Com.getList().forEach(port -> ((DefaultComboBoxModel)portName.getModel()).addElement(port));
		
		if (selected != null) {
			portName.setSelectedItem(selected);
		}
	}
	
	private static String getVersionString() {
		String v = schn27.imutest.Version.get();
		return (v != null) ? v.substring(0, 8) : "<empty>";
	}
	
	private void printToConsoleOut(String text) {
		((DefaultListModel)consoleOut.getModel()).addElement(text);
		consoleOut.ensureIndexIsVisible(consoleOut.getModel().getSize() - 1);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpen = new javax.swing.JButton();
        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        consoleIn = new javax.swing.JTextField();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        consoleOut = new javax.swing.JList();
        chartsPanel = new javax.swing.JPanel();
        portName = new javax.swing.JComboBox();
        gitVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.title")); // NOI18N
        setLocationByPlatform(true);

        btnOpen.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.btnOpen.text")); // NOI18N
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        consoleIn.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.consoleIn.text")); // NOI18N
        consoleIn.setToolTipText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.consoleIn.toolTipText")); // NOI18N
        consoleIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleInActionPerformed(evt);
            }
        });

        consoleOut.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(consoleOut);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(consoleIn))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consoleIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        chartsPanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.chartsPanel.TabConstraints.tabTitle"), chartsPanel); // NOI18N

        portName.setToolTipText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.portName.toolTipText")); // NOI18N

        gitVersion.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.gitVersion.text")); // NOI18N
        gitVersion.setToolTipText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.gitVersion.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(portName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gitVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gitVersion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOpen)
                        .addComponent(portName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
		if (link == null) {
			((DefaultListModel)consoleOut.getModel()).clear();
			charts.clear();
			
			String portNameStr = (String)portName.getSelectedItem();
			
			if (portNameStr != null) {
				link = new Link(
						portNameStr, 
						status -> java.awt.EventQueue.invokeLater(() -> charts.add(status)),
						consoleString -> java.awt.EventQueue.invokeLater(() -> printToConsoleOut(consoleString))
				);
				
				(new Thread(link)).start();
			}
        } else {
            link.stop();
            link = null;
        }

        portName.setEnabled(link == null);
        btnOpen.setText(link == null ? "Open" : "Close");
    }//GEN-LAST:event_btnOpenActionPerformed

    private void consoleInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleInActionPerformed
		consoleIn.setText("");
		if (link != null) {
			link.sendCommand(evt.getActionCommand());
		}
    }//GEN-LAST:event_consoleInActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JPanel chartsPanel;
    private javax.swing.JTextField consoleIn;
    private javax.swing.JList consoleOut;
    private javax.swing.JLabel gitVersion;
    private javax.swing.JComboBox portName;
    // End of variables declaration//GEN-END:variables

	private Link link;
	private final Charts charts;
}
